backend:
  # change name to "test-repo for testing interface locally"
  name: git-gateway
  # name: test-repo
  branch: master # Branch to update (optional; defaults to master)
  
# publish_mode: editorial_workflow
media_folder: "public/img" # Media files will be stored
public_folder: "/img"

# https://decapcms.org/docs/configuration-options/#collections

collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    extension: "mdx"
    format: "yaml-frontmatter"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      # - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", date_format: "DD-MM-YYYY" }
      - {label: "Image Principale", name: "thumbnail", widget: "image"}
      - {label: "Resumé", name: "summary", widget: "string"}
      # - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}